name = "open-tracker-dashboard-frontend"
compatibility_date = "2024-01-01"

# 静态资源配置
[site]
bucket = "."

# 环境变量配置
[vars]
API_URL = "https://api.your-domain.com"  # 需要替换为实际的API地址

# 部署配置
[env.production]
workers_dev = true
route = { pattern = "dashboard.your-domain.com/*", custom_domain = true }  # 需要替换为实际域名 